steps:
# Install dependencies
- name: node
  entrypoint: yarn
  args: ['install']
# Run tests
- name: node
  entrypoint: yarn
  args: ['build']
# Run custom commands
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "600s"